### ISSUE TITLE
Installation / path questions

### ISSUE THREAD

**Issue by hoodmane** [SpectralSequences/steenrod_calculator#1]
In `install-wasm-opt.sh` is there a reason you install to `$HOME/bin` instead of `/usr/local/bin`? Apparently you were concerned about it not existing because you say `mkdir -p $HOME/bin` but if it doesn't exist then it is almost certainly not on the path. This is the case for instance on my system, whereas `/usr/local/bin` is good. So at least we need a warning that we might have not installed it onto the path.

**Comment by hoodmane** [comment]
I see, you need sudo for `/usr/local/bin`. Not that there is anything wrong with sudo for an install script, but I guess there are legitimate reasons to avoid that.

**Comment by dalcde** [comment]
On Sat, Mar 21, 2020 at 06:57:09AM -0700, Hood Chatham wrote:
>I see, you need sudo for `/usr/local/bin`. Not that there is anything wrong with sudo for an install script, but I guess there are legitimate reasons to avoid that.

The main reason for the script is to let Travis install wasm-opt and
keep it in the cache so we don't have to re-install it.

I suppose we need instructions to tell the user to add `$HOME/bin` and
`$HOME/.cargo/bin` to `PATH`, and the second has to be done anyway.

**Comment by dalcde** [comment]
I'll solve this by adding those variables to $PATH in the build script
